spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    company:
      path: /company/**
    defense:
      path: /defense/**
    student:
      path: /student/**
    teacher:
      path: /teacher/**